name: Build_and_Publish

on: # workflow_dispatch
  push:
    branches:
      - development

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-2019]  # use windows-2019 because it still has a working fortran compiler installed
    
    steps:
      - uses: actions/checkout@v3
        with:
          ref: development
      # Used to host cibuildwheel
      - uses: actions/setup-python@v3
      
      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.12.1
      
      - name: Build wheels
        env:
          CIBW_SKIP: pp* cp36-* cp37-* *musllinux*
          CIBW_ARCHS_MACOS: x86_64
          CIBW_ARCHS_LINUX: auto64
          CIBW_ARCHS_WINDOWS: auto64
          # FC: gfortran-12
        run: |
          # if macOS, make sure to set the environment variables so that it can find gfortran-9
          if [ "$RUNNER_OS" == "macOS" ]; then
            export FC=gfortran-12
          fi
          python -m cibuildwheel --output-dir wheelhouse
        shell: bash
      - name: Print for testing
        run: ls ./wheelhouse
