name: PfyMU_macos_test

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ $default-branch ]
jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        # python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Print gfortran version
      run: |
        if [ "$RUNNER_OS" == "macOS" ]; then
          gfortran-9 --version
        else
          gfortran --version
        fi
      shell: bash
