name: test_windows

on:
  push:
    branches:
      - development
jobs:
  build:

    runs-on: windows-2019
    strategy:
      matrix:
        python-version: ['3.10']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
        cache-dependency-path: gh_actions_requirements.txt
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # install the listed requirements
        pip install -r gh_actions_requirements.txt
        # install testing requirements
        pip install -r test_requirements.txt
      shell: bash
    # - uses: awvwgk/setup-fortran@main
    #   id: setup-fortran
    #   with:
    #     compiler: gcc
    #     version: 12
    - name: Install skdh
      run: |
        # install scikit-dh
        pip install . -v
      shell: bash
    - name: print dir
      run: |
        ls c:\hostedtoolcache\windows\python\3.10.11\x64\lib\site-packages
    - name: import skdh
      run: python -c "import skdh"
    - name: Test with pytest
      run: |
        pytest test/